# Generated by Django 3.2 on 2021-06-29 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='currentdate',
        ),
    ]
